# Generated by Django 2.2.6 on 2020-12-05 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
                ('city', models.CharField(default='', max_length=70)),
                ('region', models.CharField(default='', max_length=70)),
                ('postal', models.CharField(default='', max_length=70)),
                ('country', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('status', models.CharField(choices=[(True, 'Infected'), (False, 'Cured'), ('Suspected', 'Suspected')], default='', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
