# Generated by Django 2.2.6 on 2020-12-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20201205_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hashing',
            field=models.CharField(default='', max_length=100),
        ),
    ]
